### PR TITLE
Refactor(AboutView):Improve code organization and reusability

### PR DESCRIPTION
**Pull request by bigjermaine**
- Create AboutManager to encapsulate AboutView functionality
- Improve code organization and reusability
- Separate content sections into individual methods
- Maintain existing features and layout

### CODE REVIEW

**Comment by venkatasg** [comment]
Thanks for the commits on code cleanup! Just to confirm, are these tied to any API changes that are only relevant with iOS 18?

**Comment by bigjermaine** [comment]
No it’s not tied to iOS 18

**Comment by venkatasg** [comment]
I'll look at them this weekend and merge.

**Comment by bigjermaine** [comment]
ok thanks

**Comment by bigjermaine** [comment]
please don't forget

**Comment by bigjermaine** [comment]
hello Good Day, i just wanted to remind on the review

**Comment by bigjermaine** [comment]
Good day sorry a gentle reminder

**Comment by venkatasg** [comment]
Hey I'm sorry I I've been busy with my work for last few weeks. This is a hobby for me and I can't attend to pull requests as frequently as I'd like. If you leave this open I will get to it in due course.

**Pull request closed without merging**
